; Configurazione PlatformIO per ESP32 (framework Arduino)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Cartella dello sketch ESP32 (include anche .ino, .cpp, .h)
src_dir = examples/SI47XX_06_ESP32/ESP32_TWO_ENCODERS_NO_MENU

; Usa la libreria SI4735 locale del repository
lib_extra_dirs = src

; Dipendenze esterne
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306

; Velocita' seriale monitor
monitor_speed = 115200
