[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
src_dir = examples/SI47XX_06_ESP32/ESP32_TWO_ENCODERS_NO_MENU
lib_deps =
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
lib_extra_dirs =
  src
